### ISSUE TITLE
Replace setup.py with pyproject.toml

### ISSUE THREAD

**Issue by leon1995** [Draegerwerk/sdc11073#105]
Modern python packages use a [pyproject.toml](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/) file.

Use [flit ](https://github.com/pypa/flit) as build system, because it is possible to get the version from a dynamic variable (useful when parsing from a tag)

```toml
[build-system]
requires = ["flit_core >=3.2"]
build-backend = "flit_core.buildapi"
```
